### ISSUE TITLE
gamemodeで数字を指定できるように

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#1004]
### 内容

たまに数字を使おうとしている人を見かけます。その都度教えてあげるのもいいかもしれませんが、コマンドが運営に筒抜けだということを察知されたくない (逆の立場になってみれば怖いと感じると思う) という個人的なアレを持っているので、基本無視しています。

`/g` コマンドの使用を勧めるメッセージを `/gamemode creative` などと実行したときと同様に表示されると良いかもしれません。

**Comment by book000** [comment]
> コマンドが運営に筒抜けだということを察知されたくない

これは正しい判断だと思うのでそのままお願いします

---

[当該ソースコード](https://github.com/jaoafa/MyMaid4/blob/c796f9afcb4935e3497b8f366c241870799b2ecb/src/main/java/com/jaoafa/mymaid4/event/Event_GameModeCmd.java#L45)を見ましたが、数字であろうがなかろうが g コマンドのおすすめメッセージは出しているようには見えます。

まあ、gコマンドのエイリアスとしてgamemodeを指定するのは選択肢としてありかなあとは思いますが。
