### ISSUE TITLE
SKKColorでカスタム色にカラーコードを指定できるように

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#130]
リクエストターゲット: 投票のアレ
リクエスト種別: 既存コマンド・機能に対する要望
リクエスト内容: バージョンアップに伴いチャットのカラーコードにHEXコードが使えるようになったので投票回数での四角いアレに最終的に自分の好きなHEXコード使えるようにするとよさそう

**Comment by book000** [comment]
`#000000` というような `#` から始まる4文字か9文字に対応。e.g. `/skkcolor #000000`

**Comment by kohonayoshi** [comment]
pegion、ランダムカラーにしない？

**Comment by book000** [comment]
このissueの趣旨とは別なので別に立てて

**Comment by kohonayoshi** [comment]
やっぱそうなのねok
