### ISSUE TITLE
「リスポーンアンカー」ブロックのDefault,Verified(,Regular)ユーザ使用規制

### ISSUE THREAD

**Issue by Nudonge** [jaoafa/MyMaid4#163]
リスポーンアンカーはオーバーワールドで起動して右クリックすると爆発するというブロックなので、D,V(,R)のユーザの使用を規制することを提案します。
私個人としては「ブロック自体を置くことはできるが起動はできない」または「自分の自治体でのみ使用可能」とすべきかと思います。

**Comment by Nudonge** [comment]
ちがうわハゲ

**Comment by book000** [comment]
`Edit` でタイトル書き直せる
「・・・」のEditから本文書き直せる

**Comment by Nudonge** [comment]
なるほど

**Comment by book000** [comment]
:+1:

**Comment by book000** [comment]
対応策

- 爆新地内においての本ブロックの設置を制限(DV) -> Bakushinchiプラグイン
- ワールド全体において本ブロックに対するグロウストーン？のインタラクトを制限 (全権限対象)

本ブロックをクリエイティブ環境で使うことは想定できないため、所有自治体での制限回避などはしません。

**Comment by book000** [comment]
#163 がマージされればリスポーンアンカーが爆発しなくなります。ただし、以下の動作・制約になります

- ワールド全体においてリスポーンアンカーを次の条件でクリックした際にキャンセルされます。
  - 右クリックであること
  - クリックされたブロックがリスポーンアンカーであること
  - メイン/オフハンドに持っているアイテムがグロウストーン以外である場合
  - メイン/オフハンドに持っているアイテムがグロウストーンである場合、最大チャージされていること
- 爆新地内での本ブロックの使用制限は後々やります
- デバッグ棒での本ブロックの編集ができなくなります
