### ISSUE TITLE
Default権限だと/tpコマンドが使用できない

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#189]
けんげんないよーっていわれる

**Comment by book000** [comment]
具体的に、スクショ等あったら下さい。LuckPermsの設定による権限の問題なのか、MyMaid4の実装上の問題なのか判断できかねます

**Comment by minhero-exp** [comment]
![kengennasa](https://user-images.githubusercontent.com/75877469/113709014-f62db080-971c-11eb-9049-49ce95b58ee1.PNG)

**Comment by book000** [comment]
LuckPerms側の権限設定に問題があります。 `minecraft.command.teleport` をdefault権限に付与してください
