### ISSUE TITLE
Homeコマンドのリスト機能 (/home list)

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#21]
`/home list` の実装をお願いしたい
具体的にどうこうとは言わないので、綺麗なそれっぽいものを作ってほしい。

home関連コマンド実装しているので、そのあと暇なときにお願いします

**Comment by yuuahp** [comment]
homeってdb使わないんですか

**Comment by book000** [comment]
使う。ただDB制御する部分はHomeクラス作って書いたから、そのデータをこねくりまわしてもらうだけでok

**Comment by yuuahp** [comment]
HomeクラスにHomeのresultsetを返してくれるライブラリがあるんですか
それとも自分でSQL送りますか

**Comment by book000** [comment]
うーん。ソースコード見たほうが早いだろうしsethomeとdelhomeのコマンド実装終わったらコミットするわ

**Comment by yuuahp** [comment]
廊下です

**Comment by yuuahp** [comment]
了解です

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/lib/Home.java

**Comment by yuuahp** [comment]
/listhomeではなく/home listでやる感じですか

**Comment by yuuahp** [comment]
あっ理解しました

**Comment by yuuahp** [comment]
![image](https://user-images.githubusercontent.com/53546237/111897228-21987600-8a62-11eb-91b0-61a5c4be73bc.png)
見た目こんな感じでいいですか

**Comment by book000** [comment]
いいよー。私が手をつけようか迷ったときマーカーの名前・座標で行の長さ変わっちゃうから適当にスペースいれるとか考えたけど採用するかはお任せ

**Comment by yuuahp** [comment]
何文字以上だったら...で削るとかできたらやってみます

**Comment by book000** [comment]
:nu:

**Comment by yuuahp** [comment]
homelist一応できたんですがDBがないのでテストできません...

**Comment by book000** [comment]
soreha sou

**Comment by book000** [comment]
DB環境作れってのも無理だよな～

**Comment by book000** [comment]
一旦プルリク送ってもらってこっちで確認するか…

**Comment by yuuahp** [comment]
送りました
