### ISSUE TITLE
投票への誘導メッセージにあるリンクが違う・クリックできない

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#217]
誰かが投票した際に表示される「投票をよろしくお願いします！」のメッセージにあるリンクがクリックできません。
また、minecraft.jpからの投票にも関わらず/monovoteへのリンクが表示されています。(Discord側からだと/voteになっている)
![novote](https://user-images.githubusercontent.com/75877469/114287843-57e77500-9aa5-11eb-9931-f068cad40810.PNG)

**Comment by book000** [comment]
なんでぇ…？
