### ISSUE TITLE
riderくれ

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#218]

**Comment by book000** [comment]
コマンドライブラリの仕様により、`/rider <FROM> <TO>` は `/rider ride <FROM> <TO>` になります。

**Comment by kohonayoshi** [comment]
ここでいいか分からんけど
たぶんlookingから持ってきた文章が変えられてない
![image](https://user-images.githubusercontent.com/52349485/115100545-4bb55900-9f78-11eb-803a-66e759f2417f.png)
