### ISSUE TITLE
ckの実装

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#236]
ごにょごにょ。

**Comment by book000** [comment]
関連会話: https://discord.com/channels/597378876556967936/597765518501478401/830836530070290442

- 特定秒数経過したトロッコを削除
- 今までとの互換性は一応持たせる

**Comment by kohonayoshi** [comment]
今週末ある程度実装予定。
まあそもそもバニラでも`ck nearall`にあたるようなコマンド作れそうなんですけどね(コマンド簡略化という意味では必要なんだろうけど)

たぶんこんなかんじ
`execute as @e[type=minecart,distance=..100] at @s if entity @e[type=!player,distance=0] run kill @e[distance=0]`

**Comment by kohonayoshi** [comment]
バニラで代替出来たのでもういいよね
