### ISSUE TITLE
flyspeed、ダッシュ状態(ctrl押した)ときだけ機能するようにとかはできない？

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#260]

**Comment by book000** [comment]
再起動後にflyspeedを保持しないという前提ならできないことはない
ちなみにwalkspeedは？

**Comment by kohonayoshi** [comment]
walkspeedはしなくていいと思う、flyspeedは制御が効きづらいので
上下移動に関してはどうすっか

**Comment by book000** [comment]
もしこの機能作った場合上下移動は対応しきれんです
やり方としては

1. `flyspeed set` でUUIDとスピード値を紐付ける (すぐ反映しない)
2. ダッシュ状態になったときに紐づけデータからスピード値を反映する
3. 非ダッシュ状態になったときにデフォルト値を反映する

というやり方になります

**Comment by kohonayoshi** [comment]
まああれか、荒らしの追跡とかでflyspeedは有用なだけだから通常の上下の動きは別にそこまで困ってることもないし最悪エリトラ使えば問題ない
なので実装お願いします(急がない)
