### ISSUE TITLE
サーバに入退出した時のプレイヤー数表示がほしい

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#261]
![login](https://user-images.githubusercontent.com/75877469/115108220-2e997e00-9faa-11eb-9715-8ecb5d5b8bd2.PNG)

**Comment by book000** [comment]
https://github.com/book000/MyMaid2_OLD/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_LoginLeftPlayerCountNotice.java

ファイル名は変えたほうがよさそ

**Comment by book000** [comment]
次の方法で解決できます。開発を始める前に [CONTRIBUTING](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を確認してください。

1. 機能に合ったファイル名を決めます
2. `event/<1で決めたファイル名>.java` を作成し、`org.bukkit.event.Listener` と `com.jaoafa.mymaid4.lib.EventPremise` インターフェースを実装してください
3. `description()` で説明文を `return` するよう記述します
4. [MyMaid2のコード](https://github.com/jaoafa/MyMaid2/blob/master/src/main/java/com/jaoafa/MyMaid2/Event/Event_LoginLeftPlayerCountNotice.java) を参考にし、ログイン時とログアウト時にメッセージを表示するようにプログラミングしてください。この際、非推奨となっているメソッドは `Bukkit.getServer().sendMessage` と `Component.text()` などを用いて適切に書き換えてください
