### ISSUE TITLE
Tabを押すと表示されるプレイヤーリストに様々な情報を表示する

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#275]
🙏
サーバ名、時間情報、オンラインプレイヤー数、投票回数、ログイン時間、TPS
![2021-03-10_23 19 48](https://user-images.githubusercontent.com/75877469/116193668-ad40a900-a76a-11eb-8c45-d35c87411e54.png)

**Comment by book000** [comment]
昔より難易度は下がってそうねぇ
https://www.spigotmc.org/threads/tab-footer-header-for-1-15-1.410197/

**Comment by book000** [comment]
#279
