### ISSUE TITLE
実行者にしか反映されない time と weather コマンド

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#280]
[Player](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html) の `setPlayerWeather` と `setPlayerTime` あたりで作れそうです。

バニラコマンドの引数は [time](https://minecraft.fandom.com/ja/wiki/%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89/time) と [weather](https://minecraft.fandom.com/ja/wiki/%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89/weather) あたりを参考にしてください。
全部の引数をサポートしなくてもいいとは思いますが、`/time set 6000` とか `/weather rain` とかの最低限はサポートするべきかと。

よろしく❤

time: #285

**Comment by book000** [comment]
![image](https://user-images.githubusercontent.com/8929706/116479238-45997380-a8ba-11eb-9311-fd0d58764b5c.png)

今の時刻の情報を返すみたい。ただ使う人いないなら実装しなくてもいいかもね…

あと言い忘れてたけど、サーバの時刻や天気に戻すリセット引数的なのも用意したほうがいいかも

**Comment by yuuahp** [comment]
![image](https://user-images.githubusercontent.com/53546237/116479368-7aa5c600-a8ba-11eb-8854-7ee133a6bebd.png)
これですか

**Comment by book000** [comment]
![20210429-071605-firefox-EgQ9qV9Fvw](https://user-images.githubusercontent.com/8929706/116479568-d1ab9b00-a8ba-11eb-889c-eb0a2c4bcbb7.png)
![20210429-071643-firefox-KYHr7XyTk0](https://user-images.githubusercontent.com/8929706/116479589-dcfec680-a8ba-11eb-957b-d9a48146df4c.png)

ぽいね

**Comment by book000** [comment]
あ、ごめん説明不足。

`time` と `weather` をそのまま被すほうが多分綺麗(新規とかでも気にしなくて済む)ので、`mytime` じゃなくて `time` etc でコマンド定義してください

**Comment by yuuahp** [comment]
了解です

**Comment by book000** [comment]
time: :o:

**Comment by yuuahp** [comment]
よく見たらweatherやってなかった！！！！！！！

**Comment by yuuahp** [comment]
今日〜明日でやろうと思います
