### ISSUE TITLE
/home list <Page>で<Page>のStringArgumentをIntegerArgumentに変える

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#31]
Stringで読むよりも多分綺麗

https://javadoc.commandframework.cloud/cloud/commandframework/arguments/standard/IntegerArgument.Builder.html
https://github.com/search?q=cloud.commandframework.arguments.standard.IntegerArgument&type=code

その他のArgument: https://javadoc.commandframework.cloud/cloud/commandframework/arguments/standard/package-summary.html

**Comment by book000** [comment]
ラベルに困る…明確なバグではないけどバグを生み出す原因となりうるものだし…

**Comment by book000** [comment]
関連: https://github.com/Incendo/cloud/issues/241

**Comment by yuuahp** [comment]
やります

**Comment by yuuahp** [comment]
✅
