### ISSUE TITLE
エンダードラゴンスポナーが使える

### ISSUE THREAD

**Issue by Kamesuta** [jaoafa/MyMaid4#323]
エンダードラゴンスポーンエッグとエンダードラゴンスポナーが使えます
![2021-05-04_10 08 33](https://user-images.githubusercontent.com/16362824/116950700-c5f81400-acc0-11eb-98a0-f8770fdd501e.png)
![image](https://user-images.githubusercontent.com/16362824/116950728-d7d9b700-acc0-11eb-9f01-a145436009b8.png)

▼ 終焉
![2021-05-04_10 11 57](https://user-images.githubusercontent.com/16362824/116950853-474fa680-acc1-11eb-906f-38a399104a36.png)

**Comment by kohonayoshi** [comment]
例：/give @p spawner{BlockEntityTag:{SpawnData:{id:"minecraft:ender_dragon"},SpawnPotentials:[{Weight:1,Entity:{id:"minecraft:ender_dragon"}}]}} 1
