### ISSUE TITLE
植木算?機能

### ISSUE THREAD

**Issue by yuuahp** [jaoafa/MyMaid4#326]
等間隔で街頭設置とかするときにわざわざ整数出るまで計算するのがめんどくさいので、
1.WEで選択されたブロック数を測定
2.そのブロック数を使って、整数が出るまで植木算
3.もし整数が出たら間隔ブロック数提案、出なかったら (◞‸◟)
的なコマンドを作りたいです。

**Comment by book000** [comment]
iine、コマンド名はおまかせ。`calctree` ?

もし計算に時間がかかるとかの可能性があるなら非同期でコマンド処理してもいいかもね

**Comment by yuuahp** [comment]
了解です🙏
