### ISSUE TITLE
dedmessage、設定されているにも関わらず対象範囲内で死亡しても出ないことがある

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#334]
## 不具合の説明

dedmessageで正常に脂肪メッセージが登録されているにも関わらず、指定範囲で死んだときに特殊メッセージが発生しない時がある

## スクリーンショット

![2021-05-04_18 33 31](https://user-images.githubusercontent.com/52349485/116985361-4f323980-ad07-11eb-80ea-7c7b84d0387a.png)

## チェックリスト

- [x] 既に修正されたバグではありません

**Comment by book000** [comment]
直った保証はないので、再起後再度テストを欲しい。`.0` までしか対象になってなくて、端っこのブロックが対象外扱いになってたことによるものだと思われる
