### ISSUE TITLE
額縁透過コマンド

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#342]
## 内容

`/data merge entity <TARGET> {invisible:1}` と同等の機能を持ったコマンドを作る

- WorldGuardで保護されていて、自身に編集権限がない場合範囲内の額縁などは編集不能にする

**Comment by kohonayoshi** [comment]
以下のコマンドも欲しいので、/itemflameできなコマンドで実装してほしいです。
①額縁の土台となっているブロックが無くなっても、額縁が剥がれないようにするコマンド
/data merge entity <TARGET> {Fixed:1}
②/tomap等で生成した地図はhideflagsによってmapIDが見えない状態となっているのでそれを見えるようにするのと、それを額縁に貼り付けた際に起こる「`Map`というプレイヤーネームが表示される」「勝手に地図が1段階回転する」を初期状態に戻すためのコマンド
/data merge entity @e[type=minecraft:item_frame,limit=1,sort=nearest] {Item: {tag: {display:"",HideFlags:4,ItemRotation:0}}}

**Comment by kohonayoshi** [comment]
in progress への移動の仕方がよく分からんかったので何回かやるなどしてしまってログが地獄になるなどした🙏

**Comment by kohonayoshi** [comment]
- WorldGuardで保護されていて、自身に編集権限がない場合範囲内の額縁などは編集不能にする
→この仕様を満たすやり方がとりあえず分からんので、一旦R↑までに機能を制限する。実装できた後にVにも開放
