### ISSUE TITLE
rider、プレイヤー以外のエンティティの名前を指定できない

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#345]
## 不具合の説明

エンティティの名前を指定してrider ride <target>を行っても以下のスクリーンショットのようになりできません

## スクリーンショット

![2021-05-05_21 34 02](https://user-images.githubusercontent.com/52349485/117141579-a9a3c680-ade9-11eb-8462-35ed4905153f.png)

## チェックリスト

- [x] 既に修正されたバグではありません

## 追加情報

多分1.12→1.16になるにあたって
1.12 … /summon pig ~ ~ ~ {CustomName:"ぶたまん"}
1.16 … /summon pig ~ ~ ~ {CustomName:'{"text":"ぶたまん"}'}
に変更された影響かと思います

**Comment by book000** [comment]
そもそも、/rider ride <From> <To>` の From や To はセレクターを受け付けているのですが([参考](https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/command/Cmd_Rider.java#L51))、確認しましたか？

**Comment by kohonayoshi** [comment]
ないですね。普通に脳死で作業してますね。セレックターでは動きました。余計な手間かけてすみません
