### ISSUE TITLE
絶対・相対座標の変換コマンド

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#365]
`convloc` コマンドによる座標の絶対・相対変換

- `/convloc`: 見ているコマンドブロックのコマンドを「相対座標」に変換します。
- `/convloc <relative|absolute>`: 見ているコマンドブロックのコマンドを「相対座標(relative)」か「絶対座標(absolute)」のいずれかに変換します。<relative|absolute>は短縮できます。(`/convloc r` など。サジェストでは二つのみ出す)

MyMaid3ではそれぞれのコマンドが取る座標引数のみをファイルで定義しておいて、その引数だけを処理するような形で解決したが、他の手法があれば提案・実施してほしいです。

https://github.com/jaoafa/MyMaid3/blob/master/src/main/java/com/jaoafa/MyMaid3/Command/Cmd_ConvLoc.java

**Comment by book000** [comment]
複数コマンドブロックを相対にできないので、若干使いにくい面がある
WEで一括置き換えとか、コマブロ右クリックでトグルとかか？

**Comment by kohonayoshi** [comment]
私もWEで範囲指定して//convlocしたら全部反転してくれるとかは思った
WEのブロックデータってNBT拾えるかね？？

**Comment by kohonayoshi** [comment]
edited

**Comment by book000** [comment]
> WEのブロックデータってNBT拾えるかね？？

「選択している範囲の座標一覧」を拾うことはできるような気がするから(see: wire)、それでブロック走査したらいけるんじゃないかなあ

**Comment by kohonayoshi** [comment]
あーそういう感じか…

**Comment by book000** [comment]
あとはまあ、convlocにどこまで「制限」をかけるかかなあ
Regularだし変なことしないだろって踏んでWG保護とか考えなくてもいいかしら

**Comment by book000** [comment]
方針

## コマンド

on/offはtrue/falseとかある程度エイリアスを持たせる

- `/convloc`: 見ているコマンドブロックのコマンドを「相対座標」に変換します。
- `/convloc <relative|absolute>`: 見ているコマンドブロックのコマンドを「相対座標(relative)」か「絶対座標(absolute)」のいずれかに変換します。<relative|absolute>は短縮できます。
- `/convloc click`: 専用アイテム(名前付き棒？)を持たせ、その棒でコマンドブロックをクリックすると絶対・相対座標をトグルする。相対座標が含まれている場合はまず絶対座標に変更、そうでない場合は相対座標に変更
- `/convloc select [relative|absolute]`: WEでの選択範囲を「相対座標(relative)」か「絶対座標(absolute)」で一括置き換えする。指定しない場合、相対座標に変換する。

## 変換仕組み

- 前提: コマンドと座標情報があるデータ(=コマンド構造データ)を作っておく。どうやって？それ以外の方法ないかなあ
- MyMaid3のときのデータ: [command_sheet.txt](https://github.com/jaoafa/MyMaid4/files/8792429/command_sheet.txt)

1. 入力コマンドからコマンド構造データのアイテムを取り出す
2. X, Y, Zそれぞれに該当する引数を取得
3. 相対/絶対で置き換えする
4. コマンドを置き換え？
