### ISSUE TITLE
weatherコマンドの仕様変更

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#383]
## 不具合の説明

`/weather set ...` から

- /weather rain
- /weather clear

に変更してほしい。
バニラコマンドにある程度合わせたほうがいいかと思われ
## 再現手順

> バグが発生する手順を示してください

省略
## スクリーンショット

> エラーメッセージなどのスクリーンショットがある場合はURLを添付して下さい

## 追加情報

> 何か追加情報がある場合は記載してください

## システム追加情報

- 作成者: [mine_book000 (`32ff7cdc-a1b4-450a-aa7e-6af75fe8c37c`)](https://users.jaoafa.com/32ff7cdc-a1b4-450a-aa7e-6af75fe8c37c)
- 執筆者: mine_book000

**Comment by book000** [comment]
関連: #494
