### ISSUE TITLE
`/wire`(リードとコウモリを使ったワイヤーを張る)の実装

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#385]
## コマンド概要

指定された座標に特殊なコウモリを設置し、コウモリ同士にリードを張る。

### `/wire set <posX1> <posY1> <posZ1> <posX2> <posY2> <posZ2>`
- エイリアスは`add`、`connect`
- 2点の座標が書かれている場合は2点間に対し実行。

### `/wire setwe`
- エイリアスは`addwe`、`connectwe`
- `//wand`で指定した2点間に対し実行。
- `//wand`で指定した場所が3つ以上ある場合(`//sel poly`時)はそれに対して実行。

### `/wire del <posX1> <posY1> <posZ1> <posX2> <posY2> <posZ2>`
- エイリアスは`delete`、`remove`
- `/wire set`の削除版。

### `/wire delwe`
- エイリアスは`deletewe`、`removewe`
- `//wand`で指定した2点間に対し実行。
- `//wand`で指定した場所が3つ以上ある場合(`//sel poly`時)はそれに対して実行。

### 備考

- ✅リードユニット用コウモリは、`NoAI:1b`、`Silent:1b`、`PersistenceRequired:1b`、`透明化エフェクト(継続時間1000000秒、ShowParticles:0b)`、`タグ[wireUnit]`、`(付けられている側はLeashUUID)`を付けて出現させる。
- リードユニット用コウモリの透明化エフェクト、現実時間換算で11.5日(チャンクが読み込まれてない時は変わらんかも。それでも3ヶ月程度)ぐらいで消えてしまうので、`/wire delhat`に透明化時間を伸ばす機能を追加するか、指定時間を切ると延長されるか、あるいはコウモリ以外のエンティティに変えることを検討する。
- ✅リードユニット用コウモリはユーザーからの攻撃・killを無効化させたい。あるいはkillした時にもう一方のbatもキルするようにしたい
- ✅1区間の距離は、直線距離で64m以内に制限(一般的な電線が引けるぐらい)。高圧線・吊り橋などを作る必要が出てきたら128m以内に拡張を検討する。
- 指定した区間に既にリードが張られている場合はキャンセル。3点以上の場合はめんどいので1区間でも被ってればキャンセル。また、2点間が同じ座標の場合はキャンセルすべき…？
- 今の状態だとなんか2点それぞれでリードの設置位置がちょっと変わるのでどうにかしたい(引数で変えられたらいいかもしれない)
- int型で数値が指定された場合はブロックの中心に来るように座標を調整する。double型で小数点を指定された場合はそのまま。WEでの指定も同様に座標を調整する必要がありそう

### その他メモ

```
/summon bat -2737 76 2032 {PersistenceRequired:1b,NoAI:1b,ActiveEffects:[{Id:14b,Amplifier:1b,Duration:20000000,ShowParticles:0b}],Leash: {UUID: [I; 815501299, 13386601, -1685077301, -1988759884]}}
```

**Comment by book000** [comment]
あえて言うなら `/lead` にしなくても良いのでは？
用途も違うし、 `/wire` とかにすれば

エイリアスが多い件については、多ければ多いほどサジェスト汚染が多分すごいことになるので多すぎない程度に作らないと厳しいかも。

**Comment by kohonayoshi** [comment]
文の整形jaox、たすかる
wireについては最初検討したけどleadと全く違う単語よりは覚えやすいかなと思った
エイリアスは:wakaranakumonai:

**Comment by kohonayoshi** [comment]
また、2点間が同じ座標の場合はキャンセル。を追加
