### ISSUE TITLE
コマンドフレームワーク変更の提案: JorelAli/CommandAPI

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#39]
こっちの方がドキュメントしっかりしてるし使いやすそうかなあ…と思っている。現状使ってるのだと若干物足りない部分とかもあったり。

https://github.com/JorelAli/CommandAPI

意見をください。

**Comment by book000** [comment]
@yuuahp

**Comment by book000** [comment]
現状のコードから書き換える手間はそこまでないと思います。一日あれば終わるレベルかと

**Comment by book000** [comment]
とはいえ、これ以降また同じようなことを繰りかえすのは馬鹿馬鹿しいのでもっとおすすめのものがあるならそっちも検討したいです

**Comment by book000** [comment]
なんなら書き換える作業私が全部やってもいい...

**Comment by yuuahp** [comment]
機能とかドキュメントが増えるなら私は賛成です
今日は忙しいので夕方〜夜くらいから作業に参加すると思います

**Comment by book000** [comment]
とりあえず、ブランチ別で立てて切り替えたものを作ってみます。(夕方までには！)
一旦コマンドの追加作業ストップしてもらってイベント駆動な機能の実装をお願いします

**Comment by book000** [comment]
言った手前アレだけどgコマンドすら実装できそうにないのでいったんキャンセルで。

**Comment by yuuahp** [comment]
了解です
コマンドの開発も一旦再開ですか？
