### ISSUE TITLE
Wurstを用いたjaoium所持で自動EBanされたときの処罰理由の変更

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#393]
## 対象の機能・コマンド

Wurst使用の疑い(jaoium)で自動EBanされたときの処罰理由

## 強化・改善の内容

サイトリニューアルに伴って、処罰理由を `禁止クライアントMod「Wurst」使用の疑い。方針「クライアントModの導入・利用に関する規則」の「禁止事項」への違反` から `禁止クライアントMod「Wurst」使用の疑い。サーバルール内「Modについて」の「禁止事項」への違反` などへ変更。

**Comment by book000** [comment]
対象のメッセージ文章を修正することで対応できます:

https://github.com/jaoafa/MyMaid4/blob/10cd6da59e6b4cb08c5e27fee2833a9d0aa1cbea/src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java#L259
https://github.com/jaoafa/MyMaid4/blob/10cd6da59e6b4cb08c5e27fee2833a9d0aa1cbea/src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java#L358
