### ISSUE TITLE
椅子に座る・sit・layの独自実装

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#398]
1.16.5によって一部のプラグインが死んでるので、これらを独自実装する

**Comment by kohonayoshi** [comment]
時間あればやるかもしれない(希望的観測)

**Comment by book000** [comment]
難易度が割と高いと思いますけどそれでも良いなら。

**Comment by book000** [comment]
やる

**Comment by book000** [comment]
めんどくなったのでプラグイン導入で対応: https://www.spigotmc.org/resources/poseplugin-choose-your-favorite-pose-1-15-2-1-16-5.76990/
