### ISSUE TITLE
マウスホイールクリックで複製するとツールバー判定される

### ISSUE THREAD

**Issue by yuuahp** [jaoafa/MyMaid4#404]
## 不具合の説明

マウスホイールクリックで複製するとツールバー判定されるそうです。
![image](https://user-images.githubusercontent.com/53546237/119349273-eff99080-bcd8-11eb-9964-d6ad3a9fdf48.png)

## 再現手順

> バグが発生する手順を示してください（以下を書き換え・追記してください）

1. 権限グループ「`Default?`」のプレイヤー「`miyasoku`」がマウスホイールクリックでHeadアイテム?を複製する
2. ツールバー判定でブロックされる

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 既に修正されたバグではありません
  - 修正後にサーバが再起動していない場合、反映されません。サーバを再起動してください

## 追加情報

> 何か追加情報がある場合は記載してください

**Comment by book000** [comment]
簡単には判定できないので、次の処理で判定するよう検討します

- プレイヤーのインベントリアイテムを取得
- 掴んだアイテムにマッチするアイテムを探す
- あればallow, なければdeny
