### ISSUE TITLE
wire、一定領域を離れるとなんかコウモリ消えるアホ

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#410]
## 不具合の説明

wire、一定領域を離れるとなんかコウモリ消えるアホ

## 再現手順

> バグが発生する手順を示してください（以下を書き換え・追記してください）

1. 全員が近くから離れる、あるいは近くのプレイヤー全員のゲームモードをspectatorにする
2. 消える

## スクリーンショット

> エラーメッセージなどが表示されていたり、状況が分かりやすい場合はスクリーンショット・エラーログなどを添付してください（ファイルのドラックアンドドロップで添付できます）

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 既に修正されたバグではありません
  - 修正後にサーバが再起動していない場合、反映されません。サーバを再起動してください

## 追加情報

> 何か追加情報がある場合は記載してください

mine_book000: これチャンク読み込みの何かだろ
kohonayoshi: relog

kohonayoshi さんがサーバーから退出しました

kohonayoshi さんがサーバーに参加しました
mine_book000: g3でチャンクmob読み込みアレが死んでると消えるように見える
Killing1610: rj
kohonayoshi: .
mine_book000: つまりチャンク跨いでも（そのチャンクから誰もいなくなっても）Mobが残るようにしないとダメな気がする
mine_book000: それがpresidentならわからんけど
kohonayoshi: .
mine_book000: これはローカルテスト鯖で動作頑張るしかなさそうねえ

**Comment by book000** [comment]
関連: #385
