### ISSUE TITLE
チャットに書かれているリンクにアクセスできない

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#448]
## 不具合の説明

> 不具合の内容を明確・簡潔に説明してください（以下に追記してください）

チャット欄に.を含んだ文章(例:jaoafa.com)がある場合リンクになり、「クリックすると「jaoafa.com」にアクセスします」という文章も表示されるが、実際にはリンクを押しても何も反応せずアクセスできない

## 再現手順

> バグが発生する手順を示してください（以下を書き換え・追記してください）

## スクリーンショット

> エラーメッセージなどが表示されていたり、状況が分かりやすい場合はスクリーンショット・エラーログなどを添付してください（ファイルのドラックアンドドロップで添付できます）

![image](https://user-images.githubusercontent.com/52349485/121173068-5662df00-c893-11eb-9dbe-6b6e0fbef771.png)

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 既に修正されたバグではありません
  - 修正後にサーバが再起動していない場合、反映されません。サーバを再起動してください

## 追加情報

> 何か追加情報がある場合は記載してください

**Comment by book000** [comment]
`http://` `https://` といったURLプレフィックスがないことによるものと推定
http, httpsのURLではない場合にリンク化しないようにするか、クリックするURLに`https://`をつけるか。

**Comment by book000** [comment]
間違えてクローズしました:heart:

**Comment by book000** [comment]
URLの認識パターンを変えることで多分解決できます。URLのhttpsとかスキーマを必須化してしまえば済む話だと思ってます

https://github.com/jaoafa/MyMaid4/blob/8c98c088a7f7013015113f04ce3a2612c0e421ea/src/main/java/com/jaoafa/mymaid4/lib/MyMaidLibrary.java#L80

`((?:[a-z0-9]{2,}://)?(?:(?:[0-9]{1,3}\\.){3}` → `((?:[a-z0-9]{2,}://)(?:(?:[0-9]{1,3}\\.){3}`
