### ISSUE TITLE
次の駅で停車する /nextstop コマンド

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#497]
## 内容

> 新機能・新コマンドについて、理由も併せて明確・簡潔に説明してください（以下に追記してください）
> コマンドの場合、コマンド名(例: `/dt`)や引数(例: `/dt <MarkerName>`)も併せて記載して頂けると非常に有難いです

実行すると乗っているトロッコに`nextstop`タグが付与される。`nextstop`タグは、駅を通過するか停車するかの判別に使う。

[備考]
Verified,Default権限ではtagたしか使えないので扱えるようにするための対策。
現状のわたしがつくった鉄道システムだと一定時間停車で絶対大多数が降りるのが気に食わないので、もうこうなったらバスの「次とまります」ボタンてきなのを作ってしまえという魂胆

**Comment by book000** [comment]
クローズしていいですか？
