### ISSUE TITLE
leadコマンドの謎の `[` `]`

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#502]
leadコマンドで、

> 1辺30ブロックの立方体内にある指定されたターゲットセレクターの**[**Mob**]**にリードを付けます。

というように、英文字に対して `[` `]` をつけているように見えるのですが、これは何でですか？
むしろ読みづらい気もしますが

**Comment by kohonayoshi** [comment]
なんでだとおもいます？全てには理由があるのです

**Comment by book000** [comment]
わからないから聞いているんです。いい加減にしてください…

**Comment by book000** [comment]
```
1辺30ブロックの立方体内にある指定されたターゲットセレクターのMobにリードを付けます。
```

で十分なんですよ、わざわざ`[]`で囲う必要はどこにもない(`[]`で囲まなくても同時にどんな引数が必要とされているかはわかる)
むしろ`[]`があるせいで「オプションの引数なのかな？」と誤認させてしまうことすらありうるときに、ほかのコマンドでもこの書き方をしていないのにわざわざ書いている理由が知りたいです。

**Comment by book000** [comment]
「何でですか？」と質問しているのに、「なんでだと思います？」はおかしいです。人をイラっとさせたいならいいですけど、それを求めているんですか？

**Comment by kohonayoshi** [comment]
元々の表記はエンティティだったからです。
Mobでなければleadを張ることができないけど、絶対私みたいに「アマスタに張れないなんで？？」とか聞いて来る人がいるので強調するためにわざとあの表記にしています

**Comment by book000** [comment]
うーん。
もしその質問への対策を取るならアマスタとかそういう非Mobを選択しようとした時にエラーでできねえよ！とか返すとか、そっちの方が利便性高いのでは？
そんな質問してくるような人はヘルプを読まない

**Comment by kohonayoshi** [comment]
まあせやなあ
私もとまとにできるだけ合わせた説明文の組み方をするようにはしてるけどここは気になってたので次の時に差し替えるわ

**Comment by book000** [comment]
以上。クローズ
