### ISSUE TITLE
地図をオフハンドに装備すると規制される

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#514]
## 不具合の説明

地図をオフハンドに装備すると、AntiToolbarの規制が入る。

## 再現手順

1. 権限グループ「`Default`」のプレイヤー「`kittnite2000`」がオフハンドに地図を装備する
2. AntiToolbarの警告が表示される。

**Comment by book000** [comment]
@minhero-exp 再現性がありません…。たしかに、規制記録に `FILLED_MAP` 自体はあるのですが

1. Default権限に変える
2. AntiToolbar自体が正常に動作していることを確認する(適当なアイテムをツールバーから出す)
3. 白紙の地図を手に持つ
4. 右クリックして地図化する
5. マウスでのD&DもしくはFキーでオフハンドに移動する
6. 警告なく正常に持てる

となり、問題ないように見えます。

**Comment by book000** [comment]
とりあえず、ツールバーの規制から除外したので直ったものとしてクローズします
