### ISSUE TITLE
history、addしたら#jaotanに通知する

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#518]
## 内容

> 新機能・新コマンドについて、理由も併せて明確・簡潔に説明してください（以下に追記してください）
> コマンドの場合、コマンド名(例: `/dt`)や引数(例: `/dt <MarkerName>`)も併せて記載して頂けると非常に有難いです

historyに新規内容(add)が追加されたら#jaotanに通知する

**Comment by book000** [comment]
jaotanよりLOGGERの別チャンネルかなー。
