### ISSUE TITLE
D・V権限がスペクテイターモードになろうとすると、Dynmapから表示が消えてしまう

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#528]
## 不具合の説明

スペクテイターモードになる権限がないプレイヤーがスペクテイタモードになろうとすると、スペクテイターモードの規制には成功しているものの、Dynmapから自身のアイコンが消えてしまう(hide状態になる)

## 再現手順

1. 権限グループ「`Default`・`Verified`」のプレイヤーがコマンド「`/gamemode spectator`」を実行する。(スペクテイターモードになろうとする)
2. Dynmapから表示が消える。

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/event/Event_SpectatorDynmapHide.java

ignoreCancelledをTrueにしてないからか…？あとpriorityもMONITORにしたほうがいいか…
