### ISSUE TITLE
一定時間ごとにアイテムをkillする(負荷対策)

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#535]
## 内容

> 新機能・新コマンドについて、理由も併せて明確・簡潔に説明してください（以下に追記してください）
> コマンドの場合、コマンド名(例: `/dt`)や引数(例: `/dt <MarkerName>`)も併せて記載して頂けると非常に有難いです

詳細的な
・特定のタグがついてればキルしない(`NoKill`とか`Undead`とか？)
・投げてから30秒ぐらいはキルしない
・爆新地内はキルしない(なんか特定の条件下でキルしないようにしたいよね)
→周囲3block以内にアイテムが5個以上あればキルする的な

**Comment by book000** [comment]
うーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーん

**Comment by book000** [comment]
5分でアイテムは消えるし、現状それを使ったシステムがあるのでこれは拒否します
アイテムを馬鹿みたいに吐きだす馬鹿対策であれば「一定時間ごとにアイテムをキル」ではない形で再度提案下さい
