### ISSUE TITLE
Regular権限のプレイヤーがVerified/Defaultの実行したコマンドを見ることができない

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/MyMaid4#542]
## 不具合の説明

> 不具合の内容を明確・簡潔に説明してください（以下に追記してください）

Regular権限のプレイヤーがVerified/Defaultの実行したコマンドを見ることができない

## 再現手順

> バグが発生する手順を示してください（以下を書き換え・追記してください）

1. 権限グループ「`Verified`」または「`Default`」のプレイヤーがコマンド「`/aaa bbb`」を実行する
2. 権限グループ「`Regular`」のプレイヤーには実行したコマンド「`/aaa bbb`」が表示されない

## スクリーンショット

> エラーメッセージなどが表示されていたり、状況が分かりやすい場合はスクリーンショット・エラーログなどを添付してください（ファイルのドラックアンドドロップで添付できます）

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 既に修正されたバグではありません
  - 修正後にサーバが再起動していない場合、反映されません。サーバを再起動してください

## 追加情報

> 何か追加情報がある場合は記載してください

**Comment by book000** [comment]
純粋に未実装なように見えます 

> PlayerCommandSendRegular Verified以下のコマンド実行をRegularに通知
https://github.com/jaoafa/MyMaid4/issues/4

**Comment by yuuahp** [comment]
やります🤚
