### ISSUE TITLE
jailのy座標に対する移動制限を緩和したい

### ISSUE THREAD

**Issue by 5asuk3** [jaoafa/MyMaid4#568]
## 対象の機能・コマンド

> どの機能・コマンドに対するものかを示してください（以下に追記してください）

jail(投稿先が間違っている場合建て直します)

## 強化・改善を希望する理由

> 機能・コマンドに対してなぜその強化・改善を希望するのかを示してください（以下に追記してください）

木のてっぺんまで登れないのは流石に狭すぎて囚人共の健康に悪いため。

## 強化・改善の内容

> どのように強化・改善を行うかを示してください（以下に追記してください）

被jail時のy座標移動制限の緩和

これ理由と提案の順番逆では？？？？？？？？？？？？？？？？？？？？？

**Comment by book000** [comment]
たしかに理由提案の順番逆だわ…

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/84f0feebbea1c4e756b3bc142cc724082bf7b723/src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java#L80-L124

移動制限は `src/main/java/com/jaoafa/mymaid4/event/Event_Jail.java` で実装しています。
現状は、2856 69 2888を中心として半径40ブロック以上には警告が出て行けず、50ブロック以上では強制的にテレポートしています。
緩和するならこの辺の値を上げれば緩和できます

**Comment by 5asuk3** [comment]
あー一定座標からの距離なのねーん
じゃああんま広くしすぎても都合悪いわね

**Comment by book000** [comment]
んまあ、どうせ楽園の周りに色々あるとかではないので都合悪いかどうかと言われるとそこまででもない
少し緩和してテスト鯖でどこまでいけるかテストしながらかしらね〜
