### ISSUE TITLE
ピリオドマッチでOP持ち以外で早すぎるとKickされる

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/MyMaid4#571]
## 不具合の説明

OPないと、ピリオドマッチでSPAM判定される(早すぎると)

## 再現手順

1. 権限グループ「`Verified`」のプレイヤー「`OPなしPlayer`」がコマンド「`/.`」を実行する
2. エラー「`スパム行為のため退出させられました`」が表示される

## スクリーンショット
![image](https://user-images.githubusercontent.com/65443692/132935929-8974c6c3-197b-41be-b56d-2f5cc0c2c710.png)

## チェックリスト

> `[ ]` を `[x]` にすることでチェックできます

- [x] 既に修正されたバグではありません
  - 修正後にサーバが再起動していない場合、反映されません。サーバを再起動してください
(多分)

## 追加情報

> 何か追加情報がある場合は記載してください
> jao Minecraft Server の Web サイト(`jaoafa/jaoweb`)、MyMaid4(`jaoafa/MyMaid4`) および Javajaotan2(`jaoafa/Javajaotan2`) の不具合報告や新機能の提案は各リポジトリにてお願いします。

**Comment by book000** [comment]
めも https://github.com/jaoafa/MyMaid4/blob/4be241fda494d1dff37adbeba35130d8f29db83c/src/main/java/com/jaoafa/mymaid4/event/Event_DisableKicks.java
