### ISSUE TITLE
チャット四角の色が投票数が変わっても、白色になっている

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/MyMaid4#754]
### 不具合の説明

```markdown
チャット四角の色の変わる固定の数になっても、色が変わらず、白い四角のままになっている。
```

### 再現手順

```markdown
1. 投票をする
2. 特定の投票数になる
3. 変わらず
```

### 追加情報

```markdown
https://jaoafa.com/blog/how-to-vote/
```

**Comment by book000** [comment]
メモ: 具体的な検証をする必要がありそうです。
可能性としてありうるのは

- サーバ再起動後でないと変更されない
- 条件etcの処理が間違っている

かなあと思います

@kohonayoshi @yuuahp 検証可能であればもう少し詳しい情報の検証をお願いできますか？
