### ISSUE TITLE
コマンドブロックからdtコマンドを実行できるように

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#755]
### 内容

```markdown
案内所などが設置しやすくなります。昔はできてたしできていいはず。
```

**Comment by book000** [comment]
`/tp @p TomachiCity` とかが使えるはずなのですが如何ですか…？何かエラーとか出ますか？

**Comment by minhero-exp** [comment]
`/tp @p [MakerName]` だと「エンティティが見つかりませんでした」
`/dt @p [MarkerName]` だと「dt ＠p [MarkerName]← [ 問題個所 ]」
と表示されます。

**Comment by book000** [comment]
んー…。実装仕様上は可能になっているはずなので、ちょっと検証します。

**Comment by book000** [comment]
あ、わかった。`/dt tp @p MarkerName` でお試しください。

**Comment by kohonayoshi** [comment]
FF外から失礼します。えきぱ氏がいなかったのでちょっと検証してみたところ、できました。
![image](https://user-images.githubusercontent.com/52349485/159906715-9b00c567-862b-4aa2-95bf-05953dce39d2.png)

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/0526d5f7df128ebd222c529a70ddb8bd382621d2/src/main/java/com/jaoafa/mymaid4/command/Cmd_DT.java#L76

実装ミスなようなので修正必須ですね。

**Comment by minhero-exp** [comment]
dt tpコマンドでワープできることを確認しました👍

**Comment by book000** [comment]
解決したとしてクローズします。MarkerNameサジェストがおかしい件については#756にて進行します。
