### ISSUE TITLE
ログイン・ログアウトメッセージを英語化

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#775]
### 内容

通常のログインメッセージは「◯◯がゲームに参加しました。」と日本語で表示されますが、投票によってログインメッセージが増えると「◯◯, ～～～ joined the game.」のように英語で表示されるため、通常のログインメッセージも英語(日本語でも)にすると統一感があっていいと思います。ログアウトメッセージも同様、日本語で表示されています。

**Comment by book000** [comment]
1.18より前のどこかでi18n (多言語対応)がログイン/ログアウトメッセージにも適用された影響のようです。

[event/Event_CustomJoinMessage](https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/event/Event_CustomJoinMessage.java) をいじれば解決できそうです。
投票数20未満の場合`getPlayerJoinMessage`がnullを返すので、これを英語ログインメッセージに変えればよいかと思います。

同様に、ログアウトメッセージも英語で統一してしまっていいかと。(`the New Generation` のアレが英語なのにそれ以外日本語だと微妙すぎるので…)
