### ISSUE TITLE
感圧板でRS信号を送るとクロック回路と判断されて規制される

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#797]
### 不具合の説明

感圧板・ボタンにレッドストーンを接続し、作動させた後に信号が切れるとクロック回路として判断されます。接続されているレッドストーンが2ブロック以上のときのみ発生するようです。

https://user-images.githubusercontent.com/75877469/166129834-4104f552-2b06-4b8c-b020-1a609bbd2a3b.mp4

### 再現手順

1. 感圧板、もしくはボタンにレッドストーンを接続し、動力を送る
2. 信号が切れると同時にクロック回路として判断され、レッドストーンが看板に置き換わる。

**Comment by book000** [comment]
fixed by https://github.com/jaoafa/ChuoCity/pull/61
