### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#799]
## 不具合の説明

> 不具合の内容を明確・簡潔に説明してください

クロック回路じゃないのにクロック回路って票しか出る
## 再現手順

> バグが発生する手順を示してください

## スクリーンショット

> エラーメッセージなどのスクリーンショットがある場合はURLを添付して下さい

## 追加情報

> 何か追加情報がある場合は記載してください

## システム追加情報

- 作成者: [KEISHIN_0817 (`46e62cc1-108e-41bb-a12a-97168aa14c83`)](https://users.jaoafa.com/46e62cc1-108e-41bb-a12a-97168aa14c83)
- 執筆者: KEISHIN_0817

**Comment by book000** [comment]
duplicate: #797
