### ISSUE TITLE
/g コマンドでゲームモードを変更する際、大文字を指定できない

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/MyMaid4#890]
ゲームモードを `g` コマンドで変更した際に表示されるメッセージの、ゲームモードの部分にカーソルを当てると「○○○○ にゲームモードを変更します。」と表示され、クリックすると `/g ○○○○` と実行されますが、○○の部分は大文字表記で、指定したゲームモードは存在しないとされて実行できません。

![image](https://user-images.githubusercontent.com/75877469/181903056-c674a374-439c-4e04-b192-5877e4ac0a49.png)

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/a82c12b3c0126749ece532e1dddc273913a120e9/src/main/java/com/jaoafa/mymaid4/command/Cmd_G.java#L234

ここで引数 `str` も `toLowerCase()` していないのが問題？

**Comment by book000** [comment]
@yuuahp 可能なら修正していただけると助かります

**Comment by yuuahp** [comment]
https://github.com/jaoafa/MyMaid4/pull/891 ✅
