### ISSUE TITLE
mobの建築エリア内での召喚

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#892]
## 不具合の説明

> 不具合の内容を明確・簡潔に説明してください

バケツ入りの魚を置くとそれが召喚できます。mobが
## 再現手順

> バグが発生する手順を示してください

## スクリーンショット

> エラーメッセージなどのスクリーンショットがある場合はURLを添付して下さい

## 追加情報

> 何か追加情報がある場合は記載してください

## システム追加情報

- 作成者: [AboardBear82960 (`5c426215-22d8-4268-aaa0-1d15e6e3304c`)](https://users.jaoafa.com/5c426215-22d8-4268-aaa0-1d15e6e3304c)
- 執筆者: AboardBear82960

**Comment by book000** [comment]
@minhero-exp 検証をおねがいしてもいいですか？

**Comment by book000** [comment]
これが事実であれば、ブラックリストに当該アイテム群を追加する必要あり。

**Comment by minhero-exp** [comment]
水の広がりは抑制されるものの、魚はスポーンさせることができました。(Default権限、中央市内にて)

![2022-08-02_13 51 15](https://user-images.githubusercontent.com/75877469/182294336-15bb0151-9ed6-498f-ad05-ac47ae11db1d.png)

**Comment by book000** [comment]
次のアイテムについて、Regular / Moderator / Admin以外の利用をブラックリストにより制限しました。

- フグ入りバケツ PUFFERFISH_BUCKET
- サケ入りバケツ SALMON_BUCKET
- タラ入りバケツ COD_BUCKET
- 熱帯魚入りバケツ TROPICAL_FISH_BUCKET
- ウーパールーパー入りバケツ AXOLOTL_BUCKET

解決したものとしてクローズします。
