### ISSUE TITLE
すでに頭に頭がある場合、その頭がかぶれない

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/MyMaid4#896]
### 不具合の説明

```markdown
/headして手に入れた頭をかぶるとき(/hatなし)(手動)、すでに別の頭を着てた場合、イベントリバーから取得できないものとして消去される。
```

### 再現手順

```markdown
1. 権限グループ「`Verified`」のプレイヤー「`Kinoko_2K`」がコマンド「`/head MinHero_exp`」を実行する
2. 頭にかぶる
3. 権限グループ「`Verified`」のプレイヤー「`Kinoko_2K`」がコマンド「`/head Kinoko_2K`」を実行する
4. 頭にかぶろうとすると、「ツールバーからの取得が見られるので規制しました」と表示され、そのKinoko_2Kの頭が消える
```

**Comment by book000** [comment]
検証した感じ、`head` (およびgiveコマンドなどでの入手)時に与えられるNBTタグ（UUIDでの指定orプレイヤー名での指定のみ）から、プレイヤーがそのアイテムに対して何らかの操作をした際に起きるNBTタグ置き換え（実際のプロファイルデータ）が起きて *インベントリに存在するアイテムではない* という判定処理が行われるのが原因のようです。

**Comment by book000** [comment]
…と思って `event.getCurrentItem()` と `event.getCursor()` の結果を比較し `PLAYER_HEAD` の場合に限り `name` や `uniqueId` 値を見て処理しようと思ったんですが、今回のissueとはすこし状態が異なる（再現手順を踏むとそもそも `event.getCurrentItem()` は AIR になる）ので別の方法を考えます
