### ISSUE TITLE
/debstickで手に入れたデバッグ棒を使えない

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/MyMaid4#907]
### 不具合の説明

デバッグ棒が使用できない。

### 再現手順

1. 権限グループ「`Verified`」のプレイヤー「`Kinoko_2K`」がコマンド「`/debstick`」を実行する
2. 階段ブロックに使用する
3. 何にも変わらない(表示も出ないただの棒)

### スクリーンショット

https://gyazo.com/004e903527e22aff3239f8e905ec54a5

**Comment by book000** [comment]
CoreProtectのログに残らないことを理由に、ブラックリストによってRegular未満のユーザーには利用を禁止しています。

**Comment by kinoko2k** [comment]
Verifiedは一応手に入るのでメッセージ出してほしいです。()

**Comment by minhero-exp** [comment]
Verified権限における `/debstick` の使用が制限されていなかったようですので、Regular以上のプレイヤーのみが利用できるように修正しました。

**Comment by kinoko2k** [comment]
> 各所にVerified権限でも `/debstick` が使えるという情報の記載があるようなので、随時修正します。

jao minecraft server内のルールブックにも記載してほしいです。
https://gyazo.com/845b8a1931cb28622dea23c5640ce64e
