### ISSUE TITLE
/headでUUIDを対応してほしい

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/MyMaid4#923]
### 内容

(自分だけかもしれんけど)
`/head [uuid]`として、頭取得できなかったのでほしいです。

**Comment by book000** [comment]
利用しているフレームワーク [Incendo/cloud](https://github.com/Incendo/cloud) の `OfflinePlayerArgument` に UUIDでオフラインプレイヤー情報を取得する手段がありませんので仕様です。
