### ISSUE TITLE
サバイバルで石を掘るとアイテム化されない

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#924]
## 不具合の説明

>サバイバルでブロックを掘るとアイテム化しない 不具合の内容を明確・簡潔に説明してください

## 再現手順

>1.Kinoko_2Kが`/g 0`を実行
2.Kinoko_2Kが石を掘る(木のツルハシで)
3.アイテム化しない バグが発生する手順を示してください

## スクリーンショット

> エラーメッセージなどのスクリーンショットがある場合はURLを添付して下さい

## 追加情報

> 何か追加情報がある場合は記載してください

## システム追加情報

- 作成者: [Kinoko_2K (`a0874294-e1a2-49d0-b020-02df507e7d18`)](https://users.jaoafa.com/a0874294-e1a2-49d0-b020-02df507e7d18)
- 執筆者: Kinoko_2K

**Comment by kinoko2k** [comment]
題名切れてますが、下記の通りです。
> サバイバルで石を掘るとアイテム化されない

**Comment by Omuretsu** [comment]
> 題名切れてますが、下記の通りです。

→修正しました。

**Comment by minhero-exp** [comment]
ゲームルール「doTileDrops」が `false` になっていたため、ブロックが破壊されたときにアイテムがドロップしなくなっていた模様です。とりあえず `true` に変更しました。
