### ISSUE TITLE
/flyspeedの不具合

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#941]
## 不具合の説明

> 不具合の内容を明確・簡潔に説明してください

/flyspeedコマンドの飛行速度がダッシュ状態(Ctrlキーを押していない状態)が通常の飛行速度になってしまう
## 再現手順

> バグが発生する手順を示してください

## スクリーンショット

> エラーメッセージなどのスクリーンショットがある場合はURLを添付して下さい

## 追加情報

> 何か追加情報がある場合は記載してください

## システム追加情報

- 作成者: [Micni43 (`9ad39fa0-2c16-449c-8a86-c8a3543429e9`)](https://users.jaoafa.com/9ad39fa0-2c16-449c-8a86-c8a3543429e9)
- 執筆者: Micni43

**Comment by yuuahp** [comment]
仕様じゃなかったっけ？
